### ISSUE TITLE
fbms under utils folder is unavailable for us

### ISSUE THREAD

**Issue by xianshunw** [achalddave/segment-any-moving#3]
Sorry to disturb you again. The subproject `fbms` under `utils` is not accessible for us. I have tried to search it on bitbucket, but it seems that it's private.

**Comment by achalddave** [comment]
My bad, the repo was [public](https://bitbucket.org/devalab/fbms/src/master/) as far as I can tell, but the submodule link was an ssh link rather than an https link, which was what was breaking the clone. Can you try again now? You'll most likely have to delete the repo and re-clone it from scratch.

**Comment by xianshunw** [comment]
It works now. Thanks.
